#
# Conda environment definition with dependencies
#
name: plinder
channels:
  - metalcycling
  - conda-forge
  - aivant
  - defaults
  - bioconda
dependencies:
  - reduce
    #- aivant::openstructure
  - boost=1.82
  - mmseqs2
  - foldseek
  - plip
  - pip:
    - keyrings.google-artifactregistry-auth==1.1.2
